name: "Code Style"
on: [pull_request]

jobs:
  code_style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: "Laravel Pint"
        uses: aglipanci/laravel-pint-action@2.0.0
        with:
          verboseMode: true
          testMode: true
          configPath: "./pint.json"
